name: 'compress-action-minratio'
description: 'A GitHub Action for compressing files using Brotli or GZip compression.'
author: 'sachk'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  path:
    description: 'The path containing the files to compress'
    required: true
    default: '.'
  compressors:
    description: 'List of compressors to use'
    required: false
    default: 'gzip,brotli'
  minRatio:
    description: 'Minimum compression ratio'
    required: false
    default: '1.2'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/sachk/compress-action:1'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.compressors }}
    - ${{ inputs.minRatio }}
